id: P85722CB4
initial_creation_type: input
source_metadata:
  title: Dudjom Lingpa Series
  language: es
  description: 'We present the following texts by and about the great tertön Dudjom
    Lingpa (bdud ''joms gling pa, 1835–1904):'
  volume:
    5c3d0a5cfe95455aba5974090d27f0a5:
      title: A Sukhāvatī Prayer and Aspiration
      parent: Aspiration Prayers
    8c906c9498c243f48ee0b66715e977a8:
      title: An Aspiration
      parent: Aspiration Prayers
    e0b09de9410848e980c30adeae332715:
      title: An Aspiration Prayer
      parent: Aspiration Prayers
    c5fd26994a5348f6adccad833c9fc0b3:
      title: The Biography of the Great Orgyen that Naturally Liberates On Sight
      parent: Biography
    1fb07352febc4c8eb11a9a1df1f34e28:
      title: Golden Drink (Serkyem) and Torma Offering
      parent: Offering
    4c0960da37bd4726a246a2968da9a46a:
      title: The Verse for Offering Water from the Pure Vision, An Ocean of Accomplishments
      parent: Offering
    f52950250b324c26b89d91141445669b:
      title: A Prayer
      parent: Prayers
    64fa13ffe54b4dd1ae32aea770accbf7:
      title: A Prayer to Dudjom Lingpa
      parent: Prayers
    216e0ac0610f4d78a00c4883a41c3d7f:
      title: A Prayer to Padmasambhava
      parent: Prayers
    4ea4283557094bf9a6ea1a638061c973:
      title: A Prayer to Parṇaśavarī
      parent: Prayers
    04841a98046d4e3a90e203533b6fd317:
      title: The Outer, Inner and Secret Refuge Prayer
      parent: Refuge
    5c4849e615804eeaac4721ca30c7768b:
      title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of
        Medicine Buddha'
      parent: Sādhanas
    82a067a186654f439ba279384b57fc13:
      title: Visualization and Mantra Recitation of the Great Compassionate One
      parent: Sādhanas
created_at: '2022-02-28T23:06:52.944050'
last_modified_at: '2022-02-28T23:06:52.944052'
